# -*- coding: utf-8 -*-
"""Text to speech using our own voice project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fg3e6OuKPTtfLjw4vwjoskye1kDeN7km

## Installing the required library
"""

!pip install TTS

"""## Importing the library"""

from TTS.api import TTS
from google.colab import files
from IPython.display import Javascript, display, Audio

"""## Models available in the library"""

TTS.list_models()

"""## Sample Audio and text file for Quick testing"""



""" These  are different audio whose voice will be used"""









# !pip install python-espeak

#  !sudo apt-get install espeak

tts = TTS(model_name="tts_models/multilingual/multi-dataset/your_tts", progress_bar=True, gpu=True)

with open('/content/Text-to-speech-using-our-own-voice/text.txt') as file:
  data = file.read().replace('\n', ' ')
text = data

text

# text = '''Hey there!
# I will tell you about Listed
# 1. It is building products for the creator economy.
# 2. Open in App is the most fabulous product of Listed.
# 3. Open in App is loved by 20000 influencers & brands including  Munawar Faruqui, Raj Shamani, Riva Arora, Aishwarya
# (Ranjnikant-ji’s daughter), Trakin Tech, Mamaearth etc.
# 4. There are over 55 million users of Open in App.'''

tts.tts_to_file(text, speaker_wav="/content/Text-to-speech-using-our-own-voice/sample_audio1.wav", language="en", file_path="output1.wav")

Audio('/content/output1.wav')

tts.tts_to_file(text, speaker_wav="/content/Text-to-speech-using-our-own-voice/sample_audio2.wav", language="en", file_path="output2.wav")

Audio('/content/output2.wav')

tts.tts_to_file(text, speaker_wav="/content/Text-to-speech-using-our-own-voice/sample_audio3.wav", language="en", file_path="output3.wav")

Audio('/content/output3.wav')

tts.tts_to_file(text, speaker_wav="/content/Text-to-speech-using-our-own-voice/audio_file.wav", language="en", file_path="output4.wav")

Audio('/content/output4.wav')

"""## Try with your own audio and text
## Upload the audio file here to clone the voice
"""

display(Javascript('''
  for (rule of document.styleSheets[0].cssRules){
    if (rule.selectorText=='body') {
      rule.style.fontSize = '20px'
      break
    }
  }
  '''))
print("Upload the audio file from which you want to clone the voice")
print('Make sure the audio file is in ".wav" format')

uploaded = files.upload()
file_name = list(uploaded.keys())[0]
display(Audio('/content/' + file_name, autoplay=False))

"""## 2 options available to insert text
- add text file using upload button
- insert text directly into "text" variable
"""

text = "Hindi Diwas is celebrated on 14th September each year to honour the language and the day it was declared to be one of the official languages of India."

if text=="":
  display(Javascript('''
    for (rule of document.styleSheets[0].cssRules){
      if (rule.selectorText=='body') {
        rule.style.fontSize = '20px'
        break
      }
    }
    '''))
  print("Upload the text file which is to be converted into speech")

  uploaded = files.upload()

  with open(list(uploaded.keys())[0], encoding='utf-8') as file:
    data = file.read().replace('\n', ' ')
  text = data

print('The text file contains : ')
text

tts.tts_to_file(text, speaker_wav="/content/" + file_name, language="en", file_path="your_output.wav")

"""### Voice cloned audio"""

Audio('/content/your_output.wav')

